Repository Rdeisenroth/Rubot2, pull requests merged in 2023-11, with the labels that each got.

#17 Check all guilds the bot is in on start
  src/bot.ts
Labels: bug

#18 Improve build and push GitHub Action
  .github/workflows/build.yml
  .github/workflows/docker-img.yml
Labels: enhancement

#24 Add permissions to job
  .github/workflows/docker-img.yml
Labels: bug

#33 Improve setup documentation
  README.md
  Setup.md
  docker-compose.development.yml
Labels: documentation, enhancement

#39 Improve role management
  src/commands/admin/fixverify.ts
  src/commands/admin/genverifyroles.ts
  src/commands/admin/setinternalrole.ts
  src/commands/admin/updatebotroles.ts
  src/commands/admin/updateuserroles.ts
  src/models/bot_roles.ts
Labels: enhancement
